spring:
  cloud:
    stream:
      bindings:
        chachkiesChannel:
          destination: chachkies
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      default-binder: kafka


